import Link from "next/link";
import { completeSellerOnboardingAction } from "@/app/actions/auth";
import { SellerOnboardingSubmit } from "@/components/seller-onboarding-submit";
import { requireSeller } from "@/lib/auth";

export default async function SellerOnboardingPage(){
  await requireSeller();
  return <div className="auth-card auth-card-wide optional-onboarding"><div className="auth-title"><span>همه موارد اختیاری‌اند</span><h1>دوست داری فروشگاهت رو شخصی‌تر کنیم؟</h1><p>هرچیزی را که الان نمی‌دانی خالی بگذار؛ بعداً داخل داشبورد قابل تغییر است.</p></div><form action={completeSellerOnboardingAction} className="auth-form"><div className="form-row"><label className="field"><span>نام</span><input className="input" name="firstName"/></label><label className="field"><span>نام خانوادگی</span><input className="input" name="lastName"/></label></div><div className="form-row"><label className="field"><span>شماره موبایل</span><input className="input" name="phone" type="tel"/></label><label className="field"><span>آیدی اینستاگرام</span><input className="input" name="instagramHandle" placeholder="@yourpage"/></label></div><div className="form-row"><label className="field"><span>نام فروشگاه</span><input className="input" name="storeName" placeholder="فروشگاه من"/></label><label className="field"><span>نوع فعالیت</span><select className="input" name="sellerType" defaultValue=""><option value="">انتخاب نکردن</option><option value="INFLUENCER">تولیدکننده محتوا</option><option value="DESIGNER">طراح</option><option value="BRAND">برند</option><option value="ENTREPRENEUR">آنلاین‌شاپ</option></select></label></div><label className="field"><span>توضیح کوتاه فروشگاه</span><textarea className="input" name="storeDescription" rows={3}/></label><div className="form-row"><label className="field"><span>تجربه فروش</span><select className="input" name="experienceLevel" defaultValue=""><option value="">انتخاب نکردن</option><option value="NONE">هنوز شروع نکردم</option><option value="BEGINNER">تازه‌کار</option><option value="ACTIVE">فروش فعال</option><option value="PRO">حرفه‌ای</option></select></label><label className="field"><span>رنگ برند</span><input className="input color-input" name="brandColor" type="color" defaultValue="#ef5b4c"/></label></div><div className="optional-onboarding-actions"><SellerOnboardingSubmit/><Link href="/seller/dashboard">فعلاً رد شو؛ برو به داشبورد</Link></div></form></div>;
}
