"use client";

import Link from "next/link";
import { CheckCircle2, ExternalLink, Trash2, XCircle } from "lucide-react";
import { ActionForm } from "@/components/action-form";
import { deleteReelAction, moderateReelAction } from "@/app/actions/dashboard";

type Reel = { id: string; caption: string; tags: string[]; social_url: string | null; status: string; view_count: number; media: string; storeName: string; created_at: string; rejection_reason: string | null; products: Array<{ id: string; title: string; slug: string }> };
export function AdminReelConsole({ reels }: { reels: Reel[] }) {
  const pending = reels.filter((reel) => reel.status === "PENDING"), others = reels.filter((reel) => reel.status !== "PENDING");
  const card = (reel: Reel) => <article className="admin-reel-card" key={reel.id}><video src={reel.media} controls playsInline preload="metadata"/><div><span>{reel.storeName}</span><h3>{reel.caption || "بدون توضیح"}</h3><p>{reel.products.map((product) => product.title).join("، ")}</p>{reel.tags.length>0&&<small>{reel.tags.map((tag) => `#${tag}`).join(" ")}</small>}{reel.social_url&&<a href={reel.social_url} target="_blank" rel="noopener noreferrer"><ExternalLink/> لینک سازنده</a>}<em>{reel.status === "PENDING" ? "در انتظار بررسی" : reel.status === "PUBLISHED" ? "منتشرشده" : "ردشده"} · {reel.view_count.toLocaleString("fa-IR")} بازدید</em>{reel.rejection_reason&&<small>{reel.rejection_reason}</small>}</div><div className="admin-reel-actions">{reel.status === "PENDING"&&<><ActionForm action={moderateReelAction} showSavingOverlay={false}><input type="hidden" name="reelId" value={reel.id}/><input type="hidden" name="decision" value="PUBLISHED"/><button className="admin-primary"><CheckCircle2/> تأیید و انتشار</button></ActionForm><ActionForm action={moderateReelAction} showSavingOverlay={false}><input type="hidden" name="reelId" value={reel.id}/><input type="hidden" name="decision" value="REJECTED"/><input name="reason" required minLength={3} placeholder="دلیل رد"/><button className="danger-button"><XCircle/> رد</button></ActionForm></>}<ActionForm action={deleteReelAction} showSavingOverlay={false} confirmMessage="ویدیو و فایل آن برای همیشه حذف شود؟"><input type="hidden" name="reelId" value={reel.id}/><button className="danger-button"><Trash2/> حذف کامل</button></ActionForm></div></article>;
  return <div className="admin-page"><div className="admin-page-title"><div><span>محتوای فروشندگان</span><h1>بررسی ریلز</h1></div></div><section className="admin-reels-section"><h2>در انتظار بررسی ({pending.length.toLocaleString("fa-IR")})</h2>{pending.length?<div className="admin-reels-grid">{pending.map(card)}</div>:<p className="empty-state">ویدیوی تازه‌ای در صف نیست.</p>}</section><section className="admin-reels-section"><h2>تاریخچه</h2>{others.length?<div className="admin-reels-grid">{others.map(card)}</div>:<p className="empty-state">هنوز ویدیویی بررسی نشده است.</p>}</section></div>;
}
