"use client";

import Link from "next/link";
import { Bookmark, ChevronLeft, ChevronRight, ExternalLink, Heart, MessageCircle, Play, ShoppingBag, X } from "lucide-react";
import { useEffect, useRef, useState, useTransition } from "react";
import type { Reel } from "@/lib/catalog";
import { recordReelViewAction, toggleReelInteractionAction } from "@/app/actions/dashboard";

export function ReelsGallery({reels,initialLiked=[],initialSaved=[]}:{reels:Reel[];initialLiked?:string[];initialSaved?:string[]}) {
  const [active,setActive]=useState<number|null>(null);
  const [liked,setLiked]=useState<string[]>(initialLiked);
  const [saved,setSaved]=useState<string[]>(initialSaved);
  const [,startTransition]=useTransition();
  const viewed=useRef(new Set<string>());
  useEffect(()=>{if(active===null)return;const onKey=(event:KeyboardEvent)=>{if(event.key==="Escape")setActive(null);if(event.key==="ArrowLeft")setActive((active+1)%reels.length);if(event.key==="ArrowRight")setActive((active-1+reels.length)%reels.length)};document.body.style.overflow="hidden";window.addEventListener("keydown",onKey);return()=>{document.body.style.overflow="";window.removeEventListener("keydown",onKey)}},[active,reels.length]);
  useEffect(()=>{if(active===null)return;const id=reels[active]?.id;if(!id||viewed.current.has(id))return;viewed.current.add(id);void recordReelViewAction(id)},[active,reels]);
  const toggle=(type:"like"|"save",id:string)=>{const current=type==="like"?liked:saved;const active=!current.includes(id);const next=active?[...current,id]:current.filter(item=>item!==id);if(type==="like")setLiked(next);else setSaved(next);startTransition(async()=>{const result=await toggleReelInteractionAction({reelId:id,type,active});if(!result.ok){if(type==="like")setLiked(current);else setSaved(current)}})};
  if(!reels.length)return <div className="no-results"><Play/><h3>هنوز ویدیویی منتشر نشده</h3><p>اولین ویدیوی فروشگاه‌ها به‌زودی اینجا دیده می‌شود.</p></div>;
  return <><div className="reels-row">{reels.map((reel,index)=><button onClick={()=>setActive(index)} className="reel-card" key={reel.id}><video src={reel.media} muted playsInline preload="metadata"/><span className="reel-play"><Play fill="currentColor"/></span><div><small>{reel.handle}</small><p>{reel.caption}</p></div></button>)}</div>{active!==null&&<div className="reel-overlay" role="dialog" aria-modal="true" aria-label="ویدیوهای فروشگاه"><button className="reel-close" onClick={()=>setActive(null)} aria-label="بستن"><X/></button><button className="reel-nav prev" onClick={()=>setActive((active-1+reels.length)%reels.length)} aria-label="قبلی"><ChevronRight/></button><div className="reel-modal" onWheel={(event)=>{if(Math.abs(event.deltaY)>25)setActive(event.deltaY>0?(active+1)%reels.length:(active-1+reels.length)%reels.length)}}><div className="reel-media"><video key={reels[active].id} src={reels[active].media} controls autoPlay playsInline preload="metadata"/></div><aside><header><span>{reels[active].shopName.slice(0,1)}</span><div><Link href={`/stores/${reels[active].shopSlug}`}>{reels[active].shopName}</Link><small>{reels[active].handle}</small></div></header><p>{reels[active].caption}</p>{reels[active].tags.length>0&&<div className="reel-tags">{reels[active].tags.map(tag=><span key={tag}>#{tag}</span>)}</div>}{reels[active].socialUrl&&<a className="reel-social-link" href={reels[active].socialUrl} target="_blank" rel="noopener noreferrer"><ExternalLink/> دیدن صفحه سازنده</a>}<div className="reel-actions"><button className={liked.includes(reels[active].id)?"active":""} onClick={()=>toggle("like",reels[active].id)}><Heart fill={liked.includes(reels[active].id)?"currentColor":"none"}/><span>{(reels[active].likes+(liked.includes(reels[active].id)?1:0)).toLocaleString("fa-IR")}</span></button><button><MessageCircle/><span>دیدگاه</span></button><button className={saved.includes(reels[active].id)?"active":""} onClick={()=>toggle("save",reels[active].id)}><Bookmark fill={saved.includes(reels[active].id)?"currentColor":"none"}/><span>ذخیره</span></button></div><div className="reel-products"><b>{reels[active].products.length>1?"محصولات این ویدیو":"محصول این ویدیو"}</b>{reels[active].products.map(product=><Link className="reel-product-link" href={`/products/${product.slug}`} key={product.id||product.slug}><ShoppingBag/> {product.title}<ChevronLeft/></Link>)}</div><small className="reel-help">با اسکرول، دکمه‌ها یا کلیدهای جهت برو ویدیوی بعدی.</small></aside></div><button className="reel-nav next" onClick={()=>setActive((active+1)%reels.length)} aria-label="بعدی"><ChevronLeft/></button></div>}</>;
}
